project_name: trellis
before:
  hooks:
  - go mod download
builds:
- env:
    - CGO_ENABLED=0
  ldflags:
    - -X main.updaterRepo=roots/trellis-cli
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - name: trellis-cli
    tap:
      owner: roots
      name: homebrew-tap
    folder: Formula
    homepage:  https://roots.io/trellis
    description: A CLI to manage Trellis projects
    install: |
      bin.install "trellis"
    test: |
      system "#{bin}/trellis --autocomplete-install"
      system "#{bin}/trellis -v"
