version: 2.1

orbs:
  go: circleci/go@1

jobs:
  test:
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - run: go version
      - checkout
      - go/mod-download-cached
      - go/test:
          short: true
          verbose: true

  integration-test:
    docker:
      - image: rootsdev/trellis-cli-dev
    steps:
      - run: go version
      - run: ansible --version
      - run:
          name: Trellis version
          command: git log -1 --format="%h %s %aD"
          working_directory: /test/dummy/trellis
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: make test RUN=
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
      - store_artifacts:
          path: /test/trellis-cli

  release:
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - run: go version
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

  release-test:
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - run: go version
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash -s check
      - run: curl -sL https://git.io/goreleaser | bash -s -- --snapshot --skip-publish --rm-dist

workflows:
  test:
    jobs:
      - test
      - integration-test
      - release-test
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
